# Generated by Django 5.2 on 2025-06-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=50, unique=True)),
                ('author_id', models.CharField(max_length=50)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField()),
                ('text', models.TextField()),
                ('retweet_count', models.IntegerField()),
                ('reply_count', models.IntegerField()),
                ('like_count', models.IntegerField()),
                ('quote_count', models.IntegerField()),
                ('favorite_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
