# Generated by Django 5.2 on 2025-06-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=255, unique=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('retweet_count', models.IntegerField(default=0)),
                ('favorite_count', models.IntegerField(default=0)),
                ('language', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=255)),
                ('tweet_source', models.CharField(default='Unknown', max_length=255)),
                ('geocoordinates', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
