# Generated by Django 5.2 on 2025-06-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_tweeturl'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweeturl',
            name='category',
            field=models.CharField(choices=[('education', 'Education'), ('health', 'Health'), ('transport', 'Transport'), ('security', 'Security'), ('trade_economics', 'Trade and Economics'), ('politics', 'Politics'), ('other', 'Other')], default='other', help_text='Select a category for this Tweet URL', max_length=20),
        ),
    ]
